# Generated by Django 4.2.11 on 2024-04-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_hashtag_post_hashtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name_plural': 'Hashtags'},
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.hashtag'),
        ),
    ]
