# Generated by Django 4.2.11 on 2024-04-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
